
import pandas as pd
import ast
import os
from datetime import datetime
import re

def safe_literal_eval_numpy_strings(x):
    if not isinstance(x, str) or pd.isna(x):
        if isinstance(x, dict): return x
        return {}
    try:
        cleaned_str = re.sub(r'np\.float64\((.*?)\)', r'\1', x)
        return ast.literal_eval(cleaned_str)
    except:
        return {}

def generate_cover_page(today_folder, df):
    # Try to find a Nifty chart, else use the first stock's chart as a cover image
    nifty_chart_path = os.path.abspath(os.path.join(today_folder, "ScreenShot", "nifty.png"))
    if not os.path.exists(nifty_chart_path):
            # Fallback to the first available stock if Nifty chart isn't there
        first_symbol = df.iloc[0]['Symbol'] if not df.empty else "SANDHAR"
        nifty_chart_path = os.path.abspath(os.path.join(today_folder, "ScreenShot", f"{first_symbol}.png"))

    date_str = datetime.now().strftime('%d %B, %Y')

    return f"""
    <div class="page-container cover-page">
        <div class="cover-header">
            <div class="company-logo">
                <span class="logo-icon">📈</span> MARKET<span style="color:#1a73e8">PULSE</span>
            </div>
            <div class="report-date">{date_str}</div>
        </div>

        <div class="cover-content">
            <h1 class="cover-title">NIFTY MARKET<br>ANALYSIS</h1>
            <div class="cover-subtitle">Daily Technical & Fundamental Report</div>

            <div class="cover-chart-box">
                <div class="section-header">MARKET SNAPSHOT</div>
                <div class="crop-viewport" style="height: 500px; border: 4px solid #333;">
                    <img src="file:///{nifty_chart_path}" class="chart-img" alt="Market Chart">
                </div>
            </div>

            <div class="market-summary-box">
                <h3>Market Commentary</h3>
                <p>This report provides a comprehensive analysis of technically strong stocks, breakout candidates, and fundamentally sound companies for the upcoming trading sessions.</p>
            </div>
        </div>

        <div class="cover-footer">
            Generated by Auto-Analyst Bot
        </div>
    </div>
    """

def generate_stock_html(stock_index, stock_data, today_folder):
    technical_data = stock_data.get('technical', {})
    fundamental = stock_data.get('fundametal_resullt', {})
    symbol = stock_data.get('Symbol', 'N/A')
    abs_screenshot_path = os.path.abspath(os.path.join(today_folder, "ScreenShot", f"{symbol}.png"))

    # Technical HTML
    price_keys = ['open', 'high', 'low', 'close', 'volume']
    price_html = '<div class="price-grid">'
    for key in price_keys:
        val = technical_data.get(key, 0)
        disp = f"{val:,.0f}" if key == 'volume' else f"{val:.2f}"
        price_html += f'<div class="price-item"><span class="price-label">{key.upper()}</span><span class="price-value">{disp}</span></div>'
    price_html += '</div>'

    indicators_html = '<div class="indicators-grid">'
    for indicator, value in technical_data.items():
        if indicator in price_keys: continue
        if isinstance(value, (int, float)):
            indicator_class = "overbought" if 'RSI' in indicator and value > 70 else "oversold" if 'RSI' in indicator and value < 30 else ""
            indicators_html += f'<div class="tech-item {indicator_class}"><div class="label">{indicator}</div><div class="value">{value:.2f}</div></div>'
    indicators_html += '</div>'

    # Fundamental HTML
    scores_data = fundamental.get('scores', {})
    if not scores_data and 'details' in fundamental:
            scores_data = {k: v.get('score_pct', 0) for k,v in fundamental['details'].items()}
    scores_html = "".join([f'<div class="score-card"><div class="name">{k}</div><div class="score">{v}</div></div>' for k, v in scores_data.items()])

    rating_text = fundamental.get('rating', 'N/A')
    rating_class = "rating-good" if any(x in str(rating_text).upper() for x in ["GOOD", "EXCELLENT"]) else "rating-average"

    # News HTML
    news_items = stock_data.get('news_results', {})
    news_html = ""
    # ... (Your robust news parsing logic from previous step) ...
    if isinstance(news_items, str):
        try: news_items = ast.literal_eval(news_items)
        except: news_items = []
    if isinstance(news_items, list) and news_items:
        news_rows = ""
        count = 0
        for item in news_items:
            if count >= 3: break
            if isinstance(item, str):
                try: item = ast.literal_eval(item)
                except: item = {'news': item, 'time': '', 'url': '#'}
            if not isinstance(item, dict): continue

            news_rows += f"""
            <div class="news-item">
                <div class="news-meta"><span class="news-icon">📰</span> {item.get('time', 'Recent')} <a href="{item.get('url', '#')}" target="_blank" class="news-link">Open Link ↗</a></div>
                <div class="news-text">{item.get('news', 'No details.')}</div>
            </div>"""
            count += 1
        if news_rows:
            news_html = f'<div class="section-box"><div class="section-header">LATEST NEWS</div><div class="news-container">{news_rows}</div></div>'

    return f"""
    <div class="page-container">
        <div class="header"><h1>{stock_data.get('Stock Name', 'N/A')}</h1><div class="stock-info">{symbol} | {datetime.now().strftime('%d-%m-%Y')}</div></div>
        <div class="main-price-bar"><span class="main-price">₹{stock_data.get('Price', 'N/A')}</span><span class="pct-chg">({stock_data.get('% Chg', 'N/A')})</span><span class="vol-text">Vol: {stock_data.get('Volume', 'N/A')}</span></div>
        <div class="section-box"><div class="section-header">TECHNICAL ANALYSIS</div>{price_html}{indicators_html}</div>
        <div class="section-box"><div class="section-header">FUNDAMENTAL ANALYSIS</div><div style="margin-bottom: 5px;"><span class="rating-badge {rating_class}">{rating_text}</span> <span class="risk-label" style="font-size:10px;">Risk: <strong>{fundamental.get('risk_level', 'N/A')}</strong></span></div><div class="scores-grid">{scores_html}</div></div>
        {news_html}
        <div class="chart-container"><div class="section-header">PRICE CHART</div><div class="crop-viewport"><img src="file:///{abs_screenshot_path}" class="chart-img" alt="Chart Missing"></div></div>
    </div>
    """

def create_report_html(df, top_news, filtered_stocks_list, best_stocks_list, today_folder):
    """
    Generates the complete HTML report.
    :param df: Pandas DataFrame containing the stock data.
    :param top_news: Dictionary of top news.
    :param filtered_stocks_list: List/String of technically strong stocks.
    :param best_stocks_list: List/String of best stocks.
    :param today_folder: Path to the folder containing assets (screenshots).
    :return: The complete HTML string.
    """
    
    # Data Cleaning
    columns_to_fix = ['pattern_BE_MS_3WS_ES_3BC', 'technical', 'fundametal_resullt']
    for col in columns_to_fix:
        if col in df.columns:
            df[col] = df[col].apply(safe_literal_eval_numpy_strings)
            
    cover_page_html = generate_cover_page(today_folder, df)
    all_stocks_html = "".join([generate_stock_html(i+1, row, today_folder) for i, row in df.iterrows()])

    # Generic Top News HTML Generator
    top_news_html = '<div class="news-dashboard"><div class="news-grid">'
    sorted_categories = sorted(top_news.keys())
    for index, category in enumerate(sorted_categories):
        items = top_news[category]
        if not items: continue
        color_index = index % 8
        badge_class = f"badge-{color_index}"
        display_name = category.upper() if len(category) <= 3 else category.title()
        top_news_html += f'<div class="category-column"><div class="category-header"><span class="category-badge {badge_class}">{display_name}</span><h3 class="category-title">{display_name} Updates</h3></div><ul class="news-list">'
        for item in items[:5]:
            top_news_html += f'<li class="news-item"><a href="{item.get("url", "#")}" target="_blank" class="news-headline">{item.get("headline", "No Headline")}</a><p class="news-summary">{item.get("summary", "Click to read.") or "Click to read."}</p></li>'
        top_news_html += "</ul></div>"
    top_news_html += '</div></div>'

    complete_html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        @page {{ size: A4; margin: 0; }}
        body {{ font-family: 'Helvetica', sans-serif; margin: 0; padding: 0; background: #fff; color: #222; }}

        .page-container {{ width: 210mm; height: 296mm; padding: 10mm; box-sizing: border-box; page-break-after: always; overflow: hidden; display: flex; flex-direction: column; }}

        /* --- Cover Page Styles --- */
        .cover-page {{ justify-content: space-between; background: #fdfdfd; }}
        .cover-header {{ display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #333; padding-bottom: 20px; }}
        .company-logo {{ font-size: 24px; font-weight: bold; color: #333; display: flex; align-items: center; gap: 10px; }}
        .logo-icon {{ font-size: 30px; }}
        .report-date {{ font-size: 14px; color: #666; font-weight: 600; }}

        .cover-content {{ flex-grow: 1; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; }}
        .cover-title {{ font-size: 48px; font-weight: 900; line-height: 1.1; margin: 0 0 10px 0; color: #111; letter-spacing: -1px; text-transform: uppercase; }}
        .cover-subtitle {{ font-size: 18px; color: #555; margin-bottom: 40px; font-weight: 300; }}

        .cover-chart-box {{ width: 100%; margin-bottom: 30px; }}
        .market-summary-box {{ background: #f8f9fa; border-left: 5px solid #1a73e8; padding: 20px; text-align: left; width: 100%; box-sizing: border-box; }}
        .market-summary-box h3 {{ margin: 0 0 10px 0; color: #1a73e8; font-size: 16px; }}
        .market-summary-box p {{ margin: 0; font-size: 12px; line-height: 1.5; color: #444; }}

        .cover-footer {{ text-align: center; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }}

        /* --- Standard Styles --- */
        .header {{ background: #1a73e8; color: white; padding: 8px; text-align: center; border-radius: 4px; flex-shrink: 0; }}
        .header h1 {{ margin: 0; font-size: 16px; }}
        .stock-info {{ font-size: 10px; opacity: 0.9; }}
        .main-price-bar {{ text-align: center; padding: 8px 0; border-bottom: 1px solid #eee; flex-shrink: 0; }}
        .main-price {{ font-size: 20px; font-weight: bold; }}
        .pct-chg {{ font-size: 14px; color: #28a745; margin-left: 5px; }}
        .vol-text {{ color: #666; font-size: 10px; margin-left: 10px; }}
        .section-box {{ margin-top: 8px; flex-shrink: 0; }}
        .section-header {{ font-size: 11px; font-weight: bold; color: #1a73e8; border-left: 3px solid #1a73e8; padding-left: 6px; margin-bottom: 5px; }}
        .price-grid {{ display: flex; justify-content: space-between; margin-bottom: 5px; background: #f8f9fa; padding: 4px; border-radius: 4px; }}
        .price-item {{ text-align: center; flex: 1; }}
        .price-label {{ font-size: 8px; color: #777; display: block; }}
        .price-value {{ font-size: 10px; font-weight: bold; }}
        .indicators-grid, .scores-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 3px; }}
        .scores-grid {{ grid-template-columns: repeat(3, 1fr); }}
        .tech-item, .score-card {{ border: 1px solid #eee; padding: 3px; text-align: center; border-radius: 3px; }}
        .label, .name {{ font-size: 7px; color: #888; display: block; }}
        .value, .score {{ font-size: 9px; font-weight: bold; }}
        .rating-badge {{ padding: 2px 6px; border-radius: 8px; color: white; font-size: 9px; font-weight: bold; }}
        .rating-good {{ background: #28a745; }}
        .rating-average {{ background: #ffc107; color: #000; }}
        .news-container {{ display: flex; flex-direction: column; gap: 4px; }}
        .news-item {{ background: #fdfdfd; border-left: 2px solid #ddd; padding: 4px 8px; }}
        .news-meta {{ font-size: 9px; color: #666; margin-bottom: 2px; display: flex; justify-content: space-between; }}
        .news-link {{ color: #1a73e8; text-decoration: none; font-size: 8px; font-weight: bold; }}
        .news-text {{ font-size: 10px; color: #333; line-height: 1.3; text-align: justify; }}
        .chart-container {{ margin-top: 8px; flex-grow: 1; min-height: 0; display: flex; flex-direction: column; }}
        .crop-viewport {{ flex-grow: 1; width: 100%; overflow: hidden; border: 1px solid #ddd; position: relative; background: #fdfdfd; }}
        .chart-img {{ width: 100%; position: absolute; top: -50px; left: 0; }}
        .overbought {{ color: #dc3545; }}
        .oversold {{ color: #28a745; }}

        /* Summary & News Dashboard Styles */
        .summary-container {{ width: 90%; border: 2px solid #1a73e8; border-radius: 12px; padding: 30px; background: white; margin: 20px auto; }}
        .summary-header {{ display: flex; align-items: center; gap: 15px; border-bottom: 1px solid #eee; padding-bottom: 15px; margin-bottom: 20px; }}
        .news-dashboard {{ font-family: -apple-system, sans-serif; color: #333; padding: 20px; background-color: #f4f6f9; }}
        .news-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 20px; align-items: start; }}
        .category-column {{ background: #fff; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.08); overflow: hidden; border: 1px solid #e1e4e8; display: flex; flex-direction: column; }}
        .category-header {{ padding: 12px 15px; border-bottom: 2px solid #f0f0f0; display: flex; align-items: center; background: #ffffff; }}
        .category-badge {{ text-transform: uppercase; font-size: 11px; font-weight: 800; color: #fff; padding: 4px 8px; border-radius: 4px; margin-right: 10px; }}
        .badge-0 {{ background-color: #007bff; }} .badge-1 {{ background-color: #28a745; }} .badge-2 {{ background-color: #6f42c1; }}
        .badge-3 {{ background-color: #fd7e14; }} .badge-4 {{ background-color: #e83e8c; }} .badge-5 {{ background-color: #17a2b8; }}
        .badge-6 {{ background-color: #d63384; }} .badge-7 {{ background-color: #6610f2; }}
        .category-title {{ margin: 0; font-size: 15px; font-weight: 700; color: #2c3e50; text-transform: capitalize; }}
        .news-list {{ list-style: none; padding: 0; margin: 0; }}
        .news-item {{ padding: 15px; border-bottom: 1px solid #f1f1f1; }}
        .news-item:last-child {{ border-bottom: none; }}
        .news-headline {{ display: block; font-size: 13px; font-weight: 600; color: #2c3e50; margin-bottom: 5px; text-decoration: none; }}
        .news-summary {{ font-size: 12px; color: #666; line-height: 1.5; margin: 0; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; }}
    </style>
</head>
<body>
    {cover_page_html}
    {all_stocks_html}

    <div class="page-container" style="justify-content: center; height: auto; min-height: 296mm;">
        <div class="summary-container"><div class="summary-header"><span class="icon">⚡</span><h2>TECHNICALLY STRONG STOCKS</h2></div><div> {filtered_stocks_list} </div></div>
        <div class="summary-container"><div class="summary-header"><span class="icon">⚡</span><h2>TECHNICALLY AND FUNDAMENTALLY STRONG STOCKS</h2></div><div> {best_stocks_list} </div></div>
        {top_news_html}
    </div>
</body>
</html>
"""
    return complete_html
