"""
Query Builder
==============
Single Responsibility: Use LLM to translate natural language queries
into valid SQLite SQL statements.
Does NOT execute queries, does NOT validate them.
LLM is injected as a parameter (Dependency Inversion).
"""

import re
import json
from typing import List, Dict, Any, Optional


def _build_schema_context(table_schema: List[Dict], sample_rows: List[Dict], table_name: str) -> str:
    """
    Build a concise schema description string for LLM context.
    
    Args:
        table_schema: Output from schema_ops.get_table_schema()
        sample_rows: First N rows for value reference
        table_name: Name of the table
        
    Returns:
        Formatted string describing the table
    """
    # Column definitions
    cols = []
    for col in table_schema:
        cols.append(f"  - {col['name']} ({col['type']})")
    columns_str = "\n".join(cols)

    # Sample data
    if sample_rows:
        sample_str = json.dumps(sample_rows[:3], default=str, indent=2)
    else:
        sample_str = "(no sample data available)"

    return f"""Table: "{table_name}"
Columns:
{columns_str}

Sample Data (first rows):
{sample_str}"""


def _extract_sql_from_response(response_text: str) -> Optional[str]:
    """
    Extract SQL from LLM response text.
    Handles responses wrapped in ```sql ... ``` blocks or plain text.
    """
    # Try to find SQL in code blocks first
    sql_blocks = re.findall(r"```(?:sql)?\s*\n?(.*?)\n?```", response_text, re.DOTALL | re.IGNORECASE)
    if sql_blocks:
        return sql_blocks[0].strip()

    # Otherwise, try to find a SQL statement directly
    text = response_text.strip()
    sql_keywords = ("SELECT", "INSERT", "UPDATE", "DELETE", "ALTER", "CREATE")
    for line in text.split("\n"):
        stripped = line.strip()
        if any(stripped.upper().startswith(kw) for kw in sql_keywords):
            # Collect from this line to the end or until next non-SQL line
            return stripped

    return text.strip() if text else None


def build_sql_from_query(
    llm,
    user_query: str,
    table_schema: List[Dict],
    sample_rows: List[Dict],
    table_name: str = "excel_data"
) -> str:
    """
    Send schema + user query to LLM and get back a SQL string.
    
    Args:
        llm: LangChain LLM instance (injected — Dependency Inversion)
        user_query: Natural language question from user
        table_schema: Column info from get_table_schema()
        sample_rows: First N rows from get_sample_rows()
        table_name: Name of the table to query
        
    Returns:
        Raw SQL string generated by the LLM
        
    Raises:
        ValueError: If LLM fails to produce valid SQL
    """
    from langchain_core.messages import SystemMessage, HumanMessage

    schema_context = _build_schema_context(table_schema, sample_rows, table_name)

    system_prompt = f"""You are a SQLite SQL expert. Given a database schema and a user's natural language query, 
generate ONLY a valid SQLite SQL query. 

RULES:
1. Output ONLY the SQL query — no explanations, no markdown, no commentary.
2. Use double quotes for column/table names that contain special characters.
3. Use the exact column names from the schema.
4. For computed/derived columns, use appropriate SQL expressions.
5. Always use the table name "{table_name}" in your queries.
6. For filtering, use WHERE clauses.
7. For aggregation, use GROUP BY with appropriate aggregate functions.
8. NEVER use DROP, ATTACH, DETACH, or any destructive operations.
9. NEVER generate per-row UPDATE statements. If the user wants to add/modify data for each row, use a single UPDATE with a SQL expression or CASE WHEN.
10. Keep queries SHORT. Use SQL expressions, not literal values for each row.

DATABASE SCHEMA:
{schema_context}"""

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_query),
    ]

    response = llm.invoke(messages)
    sql = _extract_sql_from_response(response.content)

    if not sql:
        raise ValueError(f"LLM did not produce a valid SQL query. Response: {response.content[:200]}")

    return sql


def build_computed_column_expression(
    llm,
    column_name: str,
    formula_description: str,
    table_schema: List[Dict],
    sample_rows: List[Dict],
    table_name: str = "excel_data"
) -> Dict[str, str]:
    """
    Generate ONLY a SQL expression for a computed column.
    
    Instead of generating full UPDATE statements with per-row values,
    the LLM returns just the SQL expression that SQLite will evaluate
    for ALL rows at once.
    
    Args:
        llm: LangChain LLM instance
        column_name: Name for the new column
        formula_description: Natural language description of the formula
        table_schema: Current table schema
        sample_rows: Sample rows for context
        table_name: Table to modify
        
    Returns:
        Dict with keys:
            - 'expression': The SQL expression (e.g., "CASE WHEN roc > 0 THEN 1 ELSE 0 END")
            - 'col_type': The SQLite column type (REAL, INTEGER, TEXT)
    """
    from langchain_core.messages import SystemMessage, HumanMessage

    schema_context = _build_schema_context(table_schema, sample_rows, table_name)

    system_prompt = f"""You are a SQLite SQL expression expert.

TASK: Generate a SQL EXPRESSION to compute a new column value from existing columns.

OUTPUT FORMAT (strict JSON, nothing else):
{{"expression": "<sql_expression>", "col_type": "<REAL|INTEGER|TEXT>"}}

RULES:
- The expression will be used in: UPDATE "{table_name}" SET "{column_name}" = <your_expression>;
- Use ONLY column names from the schema below.
- For conditional logic, use CASE WHEN ... THEN ... ELSE ... END.
- For math, use standard SQL operators (+, -, *, /, etc.).
- Column names with special characters must be in double quotes.
- Output ONLY the JSON object. No explanations, no markdown.
- NEVER output per-row values. Only SQL expressions that work on ALL rows.

DATABASE SCHEMA:
{schema_context}"""

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=f'Compute column "{column_name}" with formula: {formula_description}'),
    ]

    response = llm.invoke(messages)
    text = response.content.strip()

    # Try to parse as JSON
    # Remove code block markers if present
    text = re.sub(r"```(?:json|sql)?\s*", "", text)
    text = re.sub(r"```", "", text).strip()

    try:
        result = json.loads(text)
        if "expression" not in result:
            raise ValueError("Missing 'expression' key")
        result.setdefault("col_type", "REAL")
        return result
    except (json.JSONDecodeError, ValueError):
        # Fallback: try to extract expression from text
        # Look for a SQL expression pattern
        expr_match = re.search(r"expression[\"']?\s*:\s*[\"'](.+?)[\"']", text, re.DOTALL)
        if expr_match:
            return {"expression": expr_match.group(1), "col_type": "REAL"}
        
        # Last resort: treat the whole response as the expression
        clean = text.strip().rstrip(";")
        if clean:
            return {"expression": clean, "col_type": "REAL"}
        
        raise ValueError(f"LLM did not produce a valid expression. Response: {text[:200]}")


# ─── Legacy compatibility ───────────────────────────────────────────────────

def build_computed_column_sql(
    llm,
    column_name: str,
    formula_description: str,
    table_schema: List[Dict],
    table_name: str = "excel_data"
) -> List[str]:
    """
    LEGACY wrapper — generates ALTER + UPDATE using expression-based approach.
    Kept for backward compatibility with excel_agent tools.
    """
    # Get the expression from LLM
    result = build_computed_column_expression(
        llm, column_name, formula_description, table_schema, [], table_name
    )
    
    col_type = result.get("col_type", "REAL")
    expression = result["expression"]
    
    return [
        f'ALTER TABLE "{table_name}" ADD COLUMN "{column_name}" {col_type};',
        f'UPDATE "{table_name}" SET "{column_name}" = {expression};',
    ]
